language: r
cache: packages

install:
  - Rscript -e "install.packages('knitr')"
  - Rscript -e "install.packages('tidyverse')"

script:
  - Rscript -e "library(knitr); knit('Figures.Rmd')"

after_success:
