---
title: "R Notebook"
output: 
  html_document:
    keep_md: true 
---

```{r}
library(dplyr)
library(ggplot2)

MB231 <- read.csv("./data/MB231.csv", stringsAsFactors = FALSE) %>%
  tidyr::separate(X, into = c("matrix", "drug"), sep = " ") %>%
  mutate(matrix = as.factor(matrix)) %>%
  dplyr::select(prolifTwo, CREB, EGFR, NFkB, p38, AKT, JNK, MEK1, ERK1.2, matrix, drug)

rescaleLMsum <- function(dataIn) {
  dataIn <- select(dataIn, -matrix, -drug) %>% scale(center = TRUE, scale = TRUE) %>% data.frame

  # Applying the linear model
  model <- lm(prolifTwo ~ . + 0, data = dataIn)
  
  # Summarize the model
  print(summary(model))
}

remove3Dmatrix <- function(dataIn) {
  return(dataIn %>% filter(matrix != "sph") %>% filter(matrix != "single") %>% filter(matrix != "serum"))
}

removeOtherDrug <- function(dataIn) {
  return(dataIn %>% filter(drug != "lap") %>% filter(drug != "tems"))
}
```

The full model:

```{r}
# Scaling the phospho-measurements by z-score
MB231 %>% rescaleLMsum()
```

The model without lap or tems:

```{r}
# Scaling the phospho-measurements by z-score
MB231 %>% removeOtherDrug() %>% rescaleLMsum()
```

The model without sph or single matrices:

```{r}
# Scaling the phospho-measurements by z-score
MB231 %>% remove3Dmatrix() %>% rescaleLMsum()
```

The model without single sph matrices, lab or tems:

```{r}
# Scaling the phospho-measurements by z-score
MB231 %>% removeOtherDrug() %>% remove3Dmatrix() %>% rescaleLMsum()
```



